version: "3.8"

services:
  multi-doc-backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    image: multi-doc-backend:latest
    container_name: multi-doc-backend
    restart: always
    environment:
      - PORT=5000

    ports:
      - "${PORT}:${PORT}"

    networks:
      - web-net

  multi-doc-frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    image: multi-doc-frontend:latest
    container_name: multi-doc-frontend

    restart: always
    environment:
      - PORT=3000

    ports:
      - "${PORT}:${PORT}"

    networks:
      - web-net

  multi-doc-genai:
    build:
      context: .
      dockerfile: genai/dockerfile
    image: multi-doc-genai:latest
    container_name: multi-doc-genai:latest
    restart: always
    environment:
      - PORT=8000

    ports:
      - "${PORT}:${PORT}"

    networks:
      - web-net

networks:
  web-net:
    external: true
